spring:
  application:
    name: pethub
  mvc:
    view:
      suffix: .html

  #데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.207.45:3306/pethub?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 12345678

  #타임리프 경로 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# # Kakao Oauth2 설정
#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 4844622e49eb896d1a1f0b02d1e46dd8
#            client-secret: SgxrSETMFAJ1YkUVFv9GlpvEwW1mA9lh
#            redirect-uri: {baseIrl}/oauth2/callback/{registrationId}
#            authorization-grant-type: authorization_code
#            client-authentication-method: client_secret_post
#            scope:
#              - profile_nickname
#      # Kakao Oauth2 Provider 설정
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
    # Naver Oauth2 설정
    security:
      oauth2:
        client:
          registration:
            naver:
              client-id: QpBnbk7arcmKPKD1wYrM
              client-secret: AXFiNzxWTx
              redirect-uri: http://localhost:8081/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              scope:
                name, email, nick
          # Naver Oauth2 Provider 설정
          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response


  #Support Mail Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkdgur96@gmail.com
    password: nqke pyrb waog kgle
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true

#s3
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2UC3C7EED3L3ZOMW
      secret-key: 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
    stack:
      auto: false
    s3:
      bucket: itbank-pethub-s3

#server port 변경
server:
  port: 8081

# projecttest_oauth2

## JWT Secret Key
#secret:
#  key:ThisStatementIsJwtSecretKeyDoNotUseThisStatement