spring:
  application:
    name: pethub
  mvc:
    view:
      suffix: .html

    static:
      path:
        pattern: /static/**


  #데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.207.45:3306/pethub?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 12345678



  jwt:
    secret: vmfhaltmskdlstkfkdgodyrogkfwkdbalrogkfmkdbalaaaaaaaaaaaaaaaabbbbb

  #타임리프 경로 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  #Support Mail Service
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkdgur96@gmail.com
    password: nqke pyrb waog kgle
    properties.mail.smtp:
      auth: true
      starttls:
        enable: true
        required: true



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 762624065961-msc4b8lr47c8h42hqfldh4qsajgk446e.apps.googleusercontent.com # 발급 받은 Client ID
            client-secret: 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 # 발급 받은 Client Secret
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email

          naver:
            client-id: fNuxSy3r0deZ7hTaPmSs
            client-secret: he3ELRPmVu
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - name
              - email
              - nickname
              - mobile

#          kakao:
#            client-id: a829d59a5dfa7dbc70ea5be560ac9966
#            client-secret: SUmHVu9rQnqAISjOXEBVr775yG66ilZt
#            client-authentication-method: client_secret_post
#            authorization-grant-type: authorization_code
#            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
#              - profile_nickname
#              - profile_image
#
#            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-info-authentication-method: header
#            user-name-attribute: id

#s3
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA2UC3C7EED3L3ZOMW
      secret-key: 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
    stack:
      auto: false
    s3:
      bucket: itbank-pethub-s3

server:
  port: 8080


