spring:
  application:
    name: pethub
  mvc:
    view:
      suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.36.207.45:3306/pethub?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 12345678

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#s3
cloud:
  aws:
    credentials:
      access-key: 액세스키
      secret-key: 시크릿키
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: itbank-pethub-s3